@startuml author
!theme blueprint

title Author Aggregate

class Author <<Aggregate Root>> {
    -id: AuthorId
    -name: AuthorName
    -biography: AuthorBiography

    +{static} create(author_id: AuthorId, name: AuthorName, biography: AuthorBiography): Author

    +id(): AuthorId
    +name(): AuthorName
    +biography(): AuthorBiography

    +change_name(new_name: AuthorName): void
    +change_biography(new_biography: AuthorBiography): void
}

@enduml
